### ISSUE TITLE
Class "BasisApi\RestApi\BasisApiClient" not found

### ISSUE THREAD

**Issue by redhead95** [Yard-Team/basis-api-client-php#1]
**Issue Description:**
When trying to use the `BasisApiClient` class from the Basis API package in a Laravel project, I encountered the following error: 

```
Class 'BasisApi\RestApi\BasisApiClient' not found.
```

Upon investigating, I noticed that during the package installation, a warning was displayed:

```
Class BasisApi\RestApi\BasisApiClient located in ./vendor/basis-api/basicapp-api-client-php/src/BasicApiClient.php does not comply with PSR-4 autoloading standard. Skipping.
```

It seems that the class is not being autoloaded properly due to non-compliance with the PSR-4 autoloading standard. As a result, the class cannot be found when attempting to use it in my Laravel project.

**Expected Outcome:**
The `BasisApiClient` class should be autoloaded correctly according to the PSR-4 autoloading standard, allowing it to be used without any "Class not found" errors.

**Steps to Reproduce:**
1. Install the Basis API package in a Laravel project.
2. Attempt to use the `BasisApiClient` class in your code.
3. Encounter the error message: `Class 'BasisApi\RestApi\BasisApiClient' not found.`

**Additional Information:**
- Laravel version: "10.8.0"
- PHP version: "8.1"
- Basis API package version: "1.0.1"
- Composer version: "2.6-dev"

**Regards.**

**Comment by sadiv** [comment]
Fixed, please update it

**Comment by redhead95** [comment]
not fixed, still getting same error
i think you just need to change name of `BasicApiClient` file in the src folder to `BasisApiClient`

**Comment by sadiv** [comment]
Yes, there was a confusion with the package name. Corrected. Notice now the package is called basis-api/basis-api-client-php

**Comment by ahmed-salar-tornet** [comment]
Fixed, Working now
Thanks

**Comment by redhead95** [comment]
Fixed, Working now
Thanks
